spring.application.name=service-b
spring.config.import=optional:configserver:http://localhost:8888

# Database
spring.datasource.url=jdbc:sqlite:./data/service-b.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.sql.init.mode=always
spring.datasource.hikari.connection-init-sql=PRAGMA foreign_keys = ON

# Eureka Client Configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

server.port=8081
